# Generated by Django 4.2.1 on 2023-05-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.IntegerField()),
                ('nome_empresa', models.CharField(max_length=255)),
                ('email_empresa', models.EmailField(max_length=254)),
                ('telefone_empresa', models.IntegerField()),
            ],
        ),
    ]
