# Generated by Django 4.2.1 on 2023-05-10 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=11)),
                ('numero_processo', models.CharField(max_length=11)),
                ('numero_empenho', models.CharField(max_length=11)),
                ('objeto', models.CharField(max_length=255)),
                ('fk_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrato.empresa')),
            ],
        ),
    ]
