# Generated by Django 4.2.1 on 2023-05-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0002_contrato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='cnpj',
            new_name='cnpj_empresa',
        ),
    ]
