# Generated by Django 4.1 on 2023-05-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0004_alter_empresa_cnpj_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='email_empresa',
            field=models.CharField(max_length=11),
        ),
    ]
