# Generated by Django 4.1 on 2023-05-30 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contrato', '0006_alter_empresa_email_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='fk_fiscal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
