# Generated by Django 4.1 on 2023-05-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0007_contrato_fk_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='anx_empenho',
            field=models.FileField(null=True, upload_to='contrato/nota_de_empenho'),
        ),
    ]
