# Generated by Django 4.1 on 2023-06-01 13:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0011_contrato_cadastrado_em_empresa_cadastrado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aditivo', models.CharField(max_length=11)),
                ('numero_processo', models.CharField(max_length=11)),
                ('numero_empenho', models.CharField(max_length=11)),
                ('valor_aditivo', models.CharField(max_length=255)),
                ('objeto_aditivo', models.CharField(max_length=255)),
                ('assinado_em', models.DateField()),
                ('cadastrado_em', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fk_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrato.contrato')),
            ],
        ),
    ]
