# Generated by Django 4.1 on 2023-06-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0012_novoevento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novoevento',
            name='numero_empenho',
        ),
        migrations.RemoveField(
            model_name='novoevento',
            name='numero_processo',
        ),
    ]
