# Generated by Django 4.1 on 2023-06-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0013_remove_novoevento_numero_empenho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj_empresa',
            field=models.CharField(max_length=14),
        ),
    ]
