# Generated by Django 4.1 on 2023-06-23 18:04

import contrato.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0014_alter_empresa_cnpj_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='novoevento',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to=contrato.models.directory_path),
        ),
    ]
