# Generated by Django 4.1 on 2023-06-23 18:26

import contrato.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0015_novoevento_anexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novoevento',
            name='anexo',
        ),
        migrations.AddField(
            model_name='contrato',
            name='anx_empenho',
            field=models.FileField(null=True, upload_to=contrato.models.directory_path),
        ),
        migrations.AddField(
            model_name='novoevento',
            name='anx_empenho',
            field=models.FileField(null=True, upload_to=contrato.models.directory_path),
        ),
    ]
