# Generated by Django 4.1 on 2023-07-04 00:49

import contrato.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0017_alter_contrato_fk_fiscal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.FileField(null=True, upload_to=contrato.models.directory_path)),
                ('fk_contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contrato.contrato')),
            ],
        ),
    ]
