# Generated by Django 4.1 on 2023-07-04 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0018_anexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='anx_empenho',
        ),
        migrations.AlterField(
            model_name='anexo',
            name='fk_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contrato.novoevento'),
        ),
    ]
