# Generated by Django 4.1 on 2023-07-28 20:02

import contrato.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0019_remove_contrato_anx_empenho_alter_anexo_fk_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novoevento',
            name='anx_empenho',
        ),
        migrations.AddField(
            model_name='contrato',
            name='anx_contrato',
            field=models.FileField(blank=True, null=True, upload_to=contrato.models.directory_path),
        ),
        migrations.AddField(
            model_name='contrato',
            name='anx_empenho',
            field=models.FileField(blank=True, null=True, upload_to=contrato.models.directory_path),
        ),
        migrations.AddField(
            model_name='contrato',
            name='anx_portaria',
            field=models.FileField(blank=True, null=True, upload_to=contrato.models.directory_path),
        ),
        migrations.AddField(
            model_name='novoevento',
            name='anx',
            field=models.FileField(blank=True, null=True, upload_to=contrato.models.directory_path),
        ),
        migrations.AddField(
            model_name='novoevento',
            name='descricao',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
