# Generated by Django 4.1 on 2023-08-18 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contrato', '0020_remove_novoevento_anx_empenho_contrato_anx_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='alterado_em',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cadastrado_em',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cadastrado_em',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='novoevento',
            name='cadastrado_em',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
