# Generated by Django 4.1 on 2023-07-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0020_remove_novoevento_anx_empenho_contrato_anx_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novoevento',
            name='descricao',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
