# Generated by Django 4.1 on 2023-08-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0021_empresa_alterado_em_empresa_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ativo',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
