# Generated by Django 4.1 on 2023-08-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0021_contrato_modificado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='modificado_por',
        ),
    ]
