# Generated by Django 4.1 on 2023-08-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0022_empresa_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='ativo',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='novoevento',
            name='ativo',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
